### PR TITLE
Refactor Module drive unit to meters

### PR DESCRIPTION
**Pull request by admlvntv**
This is a much more useful value than radians for the driving motor, and was only used back when the only real module was the ModuleIOSim.

This PR does not include any changes to PID values or FF values. These must be retuned in a different PR, as this one is required for #103

### CODE REVIEW

**Review by EQMoore — APPROVED** [review]
Lgtm! Just calculation and variable changes!

**Comment by admlvntv** [comment]
@EQMoore look a little more carefully, there is actually an error I just caught. Suggest what needs to be fixed.

**Comment by EQMoore** [comment]
Still looking for a big error but why are you multiplying by 1 here?
private final double radsToMeters = 1 * (RobotConstants.get().moduleWheelDiameter() / 2);

**Comment by admlvntv** [comment]
idk tbh, but the main issue was that I also turned the turn encoders to meters as well

**Comment by admlvntv** [comment]
ok @EQMoore can you check it now?

**Comment by EQMoore** [comment]
Lgtm, checked to see if rotsToRads was reverted properly. Sorry for such a late response, I had to eat.

**Pull request merged**
