### PR TITLE
Rewrite Vision

### PR DESCRIPTION
**Pull request by admlvntv**
Vision was rewritten from scratch to hopefully no longer crash the robot when being used. It was also moved to its own subsystem, and the odometry was turned into a universal singleton so that it can be viewed and modified by vision and drive separately.

This should not be merged until tested on real robot.

### CODE REVIEW

**Comment by admlvntv** [comment]
I forgot to commit my steps along the way, sorry to whoever has to review this. Do be aware though that I deleted everything from the vision folder and rewrote it from scratch. Ignore that it says it was modified.

**Comment by admlvntv** [comment]
previous version only used closest apriltag because i was lazy

**Review by Aradig26 — APPROVED** [review]
LGTM

**Comment by admlvntv** [comment]
@Anshu-Adiga you reviewed that in 10 seconds? Please actually check if it "looks good to you"

**Comment by Aradig26** [comment]
I reviewed it on october 31st but forgot to approve

**Comment by admlvntv** [comment]
Can you double check?

**Review by Aradig26 — APPROVED** [review]
LGTM

**Comment by admlvntv** [comment]
thanks, im making a few small changes however, can you review again in like 5-10 minutes? I'll ping you when im ready

**Comment by Aradig26** [comment]
sure
also, why 1000 meters difference for MAX_POSE_DIFFERENCE_METERS? seems like its too much

**Comment by admlvntv** [comment]
perfect timing im all done

**Comment by admlvntv** [comment]
also its to essentially always use a valid target to update the robot's pose, but if we want to tune it later we can

**Review by Aradig26 — APPROVED** [review]
lgtm

**Pull request merged**
