### PR TITLE
Add Vision classes

### PR DESCRIPTION
**Pull request by AdamCraftmaster**
Allow to access loggable PhotonCameras which can access info about the best target, along with a pose estimation from that camera via AprilTags

### CODE REVIEW

**Review by theAbishek718 — APPROVED** [review]
lgtm

**Comment by AdamCraftmaster** [comment]
must be tested before merge

**Comment by AdamCraftmaster** [comment]
TODO: rewrite io classes to only use weird arrays internally

**Review by EQMoore — APPROVED** [review]
lgtm

**Pull request merged**
